FROM node:18

WORKDIR /example-app/server

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Transpile our TypeScript files to JavaScript
RUN npm run build

EXPOSE 2000

ENV NODE_ENV=production

CMD ["npm", "run", "start:prod"]