FROM node:18

WORKDIR /example-app/server

COPY package.json package-lock.json ./

RUN npm install --only=production

COPY . .

EXPOSE 2000

ENV NODE_ENV=production

CMD ["npm", "run", "start:prod"]