FROM node:18

WORKDIR /example-app/server

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 2000

ENV NODE_ENV=staging

CMD ["npm", "run", "start:staging"]