FROM node:18

WORKDIR /example-app/client

COPY package.json package-lock.json ./
# exclude dev dependencies when building for staging
RUN npm install --only=production

COPY . .

EXPOSE 2000

CMD ["npm", "run", "start:staging"]