FROM node:18

WORKDIR /example-app/client

COPY package.json package-lock.json ./
# exclude dev dependencies when building for production
RUN npm install --only=production

COPY . .

EXPOSE 2000

ENV NODE_ENV=production

CMD ["npm", "start:prod"]